<%@ page contentType="text/html;charset=UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<!doctype html><html lang="vi"><head><title>Thêm sản phẩm</title></head><body><main class="page-shell narrow"><a class="back-link" href="${pageContext.request.contextPath}/products">← Quay lại quản lý sản phẩm</a><div class="page-heading"><div><div class="eyebrow">PRODUCT · CREATE</div><h1>Thêm sản phẩm</h1></div></div>
<c:if test="${not empty error}"><div class="alert error"><c:out value="${error}"/></div></c:if><c:if test="${empty categories}"><div class="alert error">Bạn cần tạo ít nhất một danh mục trước khi thêm sản phẩm.</div><a class="button primary" href="${pageContext.request.contextPath}/category/add">Tạo danh mục</a></c:if>
<c:if test="${not empty categories}"><form class="editor-card form-stack" method="post" enctype="multipart/form-data" action="${pageContext.request.contextPath}/product/insert">
<label>Tên sản phẩm <input name="productName" maxlength="255" required value="${fn:escapeXml(productName)}"></label><div class="form-grid"><label>Giá bán <input type="number" name="unitPrice" min="0" step="0.01" required value="${fn:escapeXml(unitPrice)}"></label><label>Số lượng <input type="number" name="quantity" min="0" required value="${empty quantity ? 0 : fn:escapeXml(quantity)}"></label></div>
<label>Danh mục <select name="categoryId" required><option value="">-- Chọn danh mục --</option><c:forEach items="${categories}" var="category"><option value="${category.categoryId}" ${selectedCategoryId == category.categoryId ? 'selected' : ''}><c:out value="${category.categoryName}"/></option></c:forEach></select></label><label>Mô tả <textarea name="description" rows="5"><c:out value="${description}"/></textarea></label>
<label>Link ảnh <input type="url" name="images" maxlength="500" value="${fn:escapeXml(images)}" placeholder="https://..."></label><div class="separator"><span>hoặc</span></div><label>Tải ảnh lên <input type="file" name="imageFile" accept="image/png,image/jpeg,image/gif,image/webp"></label>
<fieldset><legend>Trạng thái</legend><label class="radio"><input type="radio" name="status" value="1" ${empty status or status == 1 ? 'checked' : ''}> Hoạt động</label><label class="radio"><input type="radio" name="status" value="0" ${not empty status and status == 0 ? 'checked' : ''}> Khóa</label></fieldset><button class="button primary" type="submit">Lưu sản phẩm</button></form></c:if>
</main></body></html>
