<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fn" uri="jakarta.tags.functions" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!doctype html><html lang="vi"><head><title>Quản lý sản phẩm</title></head><body><main class="page-shell">
<section class="page-heading"><div><div class="eyebrow">PRODUCT MANAGEMENT</div><h1>Quản lý sản phẩm</h1><p>Chỉ hiển thị sản phẩm thuộc danh mục của tài khoản hiện tại.</p></div><a class="button primary inline" href="${pageContext.request.contextPath}/product/add">+ Thêm sản phẩm</a></section>
<c:if test="${not empty success}"><div class="alert success"><c:out value="${success}"/></div></c:if><c:if test="${not empty error}"><div class="alert error"><c:out value="${error}"/></div></c:if>
<div class="table-card"><table><thead><tr><th>#</th><th>Ảnh</th><th>Sản phẩm</th><th>Danh mục</th><th>Giá / SL</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
<c:forEach items="${products}" var="product"><c:choose><c:when test="${fn:startsWith(product.images, 'http://') or fn:startsWith(product.images, 'https://')}"><c:set var="productImage" value="${product.images}"/></c:when><c:when test="${not empty product.images}"><c:url var="productImage" value="/image"><c:param name="fname" value="${product.images}"/></c:url></c:when><c:otherwise><c:set var="productImage" value="${pageContext.request.contextPath}/assets/default-category.svg"/></c:otherwise></c:choose>
<tr><td>${product.productId}</td><td><img class="category-thumb" src="${fn:escapeXml(productImage)}" alt="Ảnh"></td><td><strong><c:out value="${product.productName}"/></strong><small>Tạo: ${product.createdDate}</small></td><td><c:out value="${product.category.categoryName}"/></td><td><fmt:formatNumber value="${product.unitPrice}" type="number" maxFractionDigits="0"/> ₫<small>${product.quantity} sản phẩm</small></td><td><span class="status ${product.status == 1 ? 'active' : 'locked'}">${product.status == 1 ? 'Hoạt động' : 'Khóa'}</span></td><td class="actions"><a href="${pageContext.request.contextPath}/product/edit?id=${product.productId}">Sửa</a><a class="delete" onclick="return confirm('Xóa sản phẩm này?')" href="${pageContext.request.contextPath}/product/delete?id=${product.productId}">Xóa</a></td></tr></c:forEach>
<c:if test="${empty products}"><tr><td colspan="7" class="empty-state">Chưa có sản phẩm.</td></tr></c:if></tbody></table></div>
<c:if test="${totalPages > 1}"><nav class="pagination"><c:forEach begin="1" end="${totalPages}" var="number"><a class="${number == page ? 'current' : ''}" href="${pageContext.request.contextPath}/products?page=${number}">${number}</a></c:forEach></nav></c:if>
</main></body></html>
